"""Audit credit-card churn data before choosing a retention model.

Reproduces baseline statistical integrity in Customer_Churn_Practice.pdf,
page 4. Full-file counts are descriptive; feature EDA belongs on training rows.
"""

import argparse
import json
from pathlib import Path

import matplotlib
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt


CASE_DIR = Path(__file__).resolve().parent
TARGET = "Attrition_Flag"
LABELS = {"Existing Customer": 0, "Attrited Customer": 1}


def summarize(data):
    """Keep missing cells, Unknown categories, and duplicate profiles distinct."""
    if not {"CLIENTNUM", TARGET}.issubset(data.columns) or data.empty:
        raise ValueError("Nonempty data with CLIENTNUM and Attrition_Flag required")
    clean = data.replace(r"^\s*$", pd.NA, regex=True)
    if clean[TARGET].isna().any() or not clean[TARGET].isin(LABELS).all():
        raise ValueError("Missing or unsupported Attrition_Flag label")
    if clean["CLIENTNUM"].isna().any() or clean["CLIENTNUM"].duplicated().any():
        raise ValueError("CLIENTNUM must be present and unique")
    counts = clean[TARGET].value_counts().reindex(LABELS, fill_value=0)
    excluded = [
        column for column in clean.columns
        if column == "CLIENTNUM"
        or column.startswith("Naive_Bayes_Classifier_Attrition_Flag_")
    ]
    missing = clean.isna().sum()
    unknown = clean.eq("Unknown").sum()
    return {
        "rows": len(clean),
        "columns": len(clean.columns),
        "unique_customer_ids": int(clean["CLIENTNUM"].nunique()),
        "class_counts": {label: int(counts[label]) for label in LABELS},
        "churn_share": float(counts["Attrited Customer"] / len(clean)),
        "always_stay_accuracy": float(counts["Existing Customer"] / len(clean)),
        "always_stay_recall": 0.0 if counts["Attrited Customer"] else None,
        "missing_cells": int(missing.sum()),
        "missing_by_column": {c: int(n) for c, n in missing.items() if n},
        "unknown_by_column": {c: int(n) for c, n in unknown.items() if n},
        "duplicate_profiles": int(clean.drop(columns=excluded).duplicated().sum()),
        "excluded_predictor_columns": excluded,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data", type=Path, default=CASE_DIR / "data/BankChurners.csv",
        help="Source CSV; defaults to this case's BankChurners.csv",
    )
    args = parser.parse_args()
    data = pd.read_csv(args.data, dtype="string")
    metrics = summarize(data)
    outputs = CASE_DIR / "outputs"
    figures = CASE_DIR / "figures"
    outputs.mkdir(exist_ok=True)
    figures.mkdir(exist_ok=True)
    (outputs / "baseline_metrics.json").write_text(
        json.dumps(metrics, indent=2, allow_nan=False) + "\n", encoding="utf-8"
    )

    counts = list(metrics["class_counts"].values())
    fig, ax = plt.subplots(figsize=(7, 4.5))
    bars = ax.bar(["Retained", "Attrited"], counts, color=["#25638a", "#b34f30"])
    ax.bar_label(bars, labels=[
        f"{n:,}\n({n / metrics['rows']:.2%})" for n in counts
    ], padding=5)
    ax.set(title="Credit-card churn: observed class balance", ylabel="Customers")
    ax.set_ylim(0, max(counts) * 1.22)
    ax.spines[["top", "right"]].set_visible(False)
    fig.text(0.5, 0.02, "Historical sample; no monthly churn horizon established",
             ha="center", fontsize=9)
    fig.tight_layout(rect=(0, 0.05, 1, 1))
    fig.savefig(figures / "baseline_class_balance.png", dpi=160)
    plt.close(fig)

    unknown_rows = "\n".join(
        f"| `{column}` | {count:,} | {count / metrics['rows']:.2%} |"
        for column, count in metrics["unknown_by_column"].items()
    ) or "| None | 0 | 0.00% |"
    recall = metrics["always_stay_recall"]
    recall_text = f"{recall:.2%}" if recall is not None else "Undefined (no churners)"
    report = f"""# Credit-card Baseline Study

Source: [Customer_Churn_Practice.pdf, page 4](<Customer_Churn_Practice.pdf#page=4>).
Input: `{args.data.name}`. Generated by `analyze.py`; raw data is unchanged.

## Verified results

| Check | Result |
|---|---:|
| Rows | {metrics['rows']:,} |
| Columns | {metrics['columns']} |
| Unique customer IDs | {metrics['unique_customer_ids']:,} |
| Retained customers | {counts[0]:,} |
| Attrited customers | {counts[1]:,} |
| Attrition prevalence | {metrics['churn_share']:.2%} |
| Always-stay accuracy | {metrics['always_stay_accuracy']:.2%} |
| Always-stay churn recall | {recall_text} |
| Missing cells, including blank strings | {metrics['missing_cells']:,} |
| Repeated profiles beyond first occurrence | {metrics['duplicate_profiles']:,} |

Profiles exclude customer ID and target-derived classifier outputs, but retain
the observed target. Repeated profiles require review before splitting.
Missing-cell counts by column are saved in `outputs/baseline_metrics.json`.

![Observed class balance](figures/baseline_class_balance.png)

## Unknown categories

| Field | Unknown customers | Share of all rows |
|---|---:|---:|
{unknown_rows}

`Unknown` is an explicit category, distinct from a missing cell. Keep it for the
baseline; fit any later imputers inside training folds only. Counts above may
overlap across customers and should not be added to estimate unique people.

## Problems and next actions

- **Imbalance:** high always-stay accuracy hides missed churners. Use average
  precision and churn precision/recall for subsequent model evaluation.
- **Incomplete demographic information:** preserve Unknown categories and later
  assess their coverage on training data.
- **Target leakage:** exclude CLIENTNUM and both Naive Bayes output columns from
  predictors. This study only audits data; no model inputs have been fitted.
- **Time limitation:** the supplied case lacks dated snapshots and event cutoffs.
  Historical class counts cannot demonstrate future stability or monthly churn.
- **Next step:** establish the practice's stratified train/validation/test split
  before transaction-activity EDA (page 5). EDA must use training records only.

The practice uses a class-weighted forest. ADASYN remains the preferred later
oversampling comparison, fitted only within training folds and checked for
unrealistic mixed-category interpolation. No oversampling is applied to this audit.

## Reproduce

From repository root:

```bash
python3 w9/analyze.py
python3 w9/test_analyze.py
```

This step reports descriptive integrity only. It does not establish numeric
feature validity, model quality, treatment effectiveness, or financial returns.
"""
    (CASE_DIR / "BASELINE_REPORT.md").write_text(report, encoding="utf-8")
    print(json.dumps(metrics, indent=2))
    print("Saved BASELINE_REPORT.md, outputs/baseline_metrics.json, and class chart.")


if __name__ == "__main__":
    main()
